Repository thdwlsgus0/help-task, pull requests merged in 2024-08, with the labels that each got.

#9 FE 폴더 구조 구축
  client/.env.template
  client/package-lock.json
  client/package.json
  client/public/fonts/.gitkeep
  client/public/images/.gitkeep
  client/public/svgs/.gitkeep
  client/src/apis/.gitkeep
  client/src/app/admin/page.tsx
  client/src/app/home/page.tsx
  client/src/app/login/page.tsx
  client/src/app/login/redirect/page.tsx
  client/src/app/register/page.tsx
  client/src/components/common/.gitkeep
  client/src/constants/business.constants.tsx
  client/src/constants/develop.constants.tsx
  client/src/container/.gitkeep
  client/src/hooks/.gitkeep
  client/src/styles/.gitkeep
  client/src/utils/.gitkeep
  client/yarn.lock
Labels: environment

#11 [FE] 프론트엔드 코드 포맷팅 설정
  .gitignore
  .husky/pre-commit
  client/.eslintrc.json
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/tsconfig.json
  client/yarn.lock
  package.json
  yarn.lock
Labels: FE, environment

#12 [FE] 전역 스타일 적용
  client/.eslintrc.json
  client/.nvmrc
  client/package-lock.json
  client/package.json
  client/src/app/globals.css
  client/src/app/home/page.tsx
  client/src/app/layout.module.scss
  client/src/app/layout.tsx
  client/src/app/page.module.css
  client/src/app/page.tsx
  client/src/styles/.gitkeep
  client/src/styles/global.scss
  client/src/styles/mixin.scss
  client/tsconfig.json
  client/yarn.lock
Labels: FE, environment

#16 api fetcher 추상화
  client/.env.template
  client/.eslintrc.json
  client/package.json
  client/src/apis/.gitkeep
  client/src/apis/fetcher.ts
  client/src/constants/develop.constants.tsx
  client/yarn.lock
  package.json
  yarn.lock
Labels: FE, feature
